// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dummy.sql

package repository

import (
	"context"
)

const getDummy = `-- name: GetDummy :one
SELECT 1::int AS dummy_value
`

func (q *Queries) GetDummy(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, getDummy)
	var dummy_value int32
	err := row.Scan(&dummy_value)
	return dummy_value, err
}
