// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Profile struct {
	ID                 uuid.UUID    `json:"id"`
	Name               string       `json:"name"`
	Gender             string       `json:"gender"`
	GenderProbability  float64      `json:"gender_probability"`
	SampleSize         int32        `json:"sample_size"`
	Age                int32        `json:"age"`
	AgeGroup           string       `json:"age_group"`
	CountryID          string       `json:"country_id"`
	CountryProbability float64      `json:"country_probability"`
	CreatedAt          time.Time    `json:"created_at"`
	UpdatedAt          sql.NullTime `json:"updated_at"`
}
